<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function speech_theme() {
  return [
    'conference_call' => [
      'variables' => [
        'form' => NULL,
        'path' => NULL,
      ],
    ],
    'call_history' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function speech_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#submit'][] = 'speech_login_form_submit';
  }
}

/**
 * Custom submit handler for the login form.
 */
function speech_login_form_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('<front>');
}
