<?php

/**
 * Implements hook_theme().
 */
function speech_theme() {
  return [
    'conference_call' => [
      'variables' => [
        'form' => NULL,
        'path' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function speech_preprocess_page(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'speech.call') {
    $variables['#attached']['library'][] = 'speech/conference_call';
  }

}
